In [2]:
import pandas as pd
from db.connection import get_engine

In [3]:
engine=get_engine()

In [5]:
users_df=pd.read_sql("select * from app.users u",engine)

In [6]:
projects_df=pd.read_sql("select * from app.projects p",engine)

In [7]:
projects_df.head()

,id,user_id,title,created_at,project_description,budget
0,1,1,Clients Project,2026-04-04 11:54:40.959623,Fix Basic CRM Module,2000.5
1,2,1,Medication Project,2026-04-04 11:54:40.959623,Central Stock remaining to be done,3052.0
2,3,1,Website,2026-04-05 10:14:02.904872,Company website,1000.0
3,4,1,Mobile App,2026-04-05 10:14:02.904872,iOS App,2000.0
4,5,2,Eshop,2026-04-05 10:14:02.904872,Online store,1500.0

In [9]:
merged_df=users_df.merge(projects_df,left_on="id",right_on="user_id",how="inner")

In [12]:
results_df=(merged_df.groupby(["id_x","name","surname"])["budget"].sum().reset_index())

In [13]:
results_df

   id_x         name surname  budget
0     1  Development    User  8052.5
1     2    Marketing    Team  1500.0
2     3   Operations    Team  4300.0

In [17]:
results_df=results_df.sort_values(by="budget",ascending=False)

In [18]:
results_df.to_sql("users_total_budget",engine,schema="app",if_exists="replace",index=False)

3